version: "3"
name: protected-echo

services:
  echo:
    build: ./echo
    ports:
      - "10100:8080"
    depends_on:
      - keycloak

  postgres:
    image: "postgres:13.2"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/
    ports:
      - "10101:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=keycloak

  keycloak:
    image: "jboss/keycloak:15.0.2"
    depends_on:
      - postgres
    ports:
      - "10102:8080"
      - "10103:8787"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
      - DEBUG=true
      - DEBUG_PORT='*:8787'
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=user
      - DB_PASSWORD=pass
      - TZ=Europe/Warsaw
